- name: Determine target_interface
  ansible.builtin.set_fact:
    install_dummy: false
    last_octet: "{{ (ansible_default_ipv4.address | split('.')).3 }}"
    target_interface: >-
      {{ ansible_default_ipv4.interface }}

- name: Feedback to user
  ansible.builtin.debug:
    msg: "Last octet is: {{ last_octet }}"

- name: Check for existence of smb.conf
  ansible.builtin.stat:
    path: /etc/samba/smb.conf
  register: smb_conf

- name: Check for status of samba-ad-dc service
  ansible.builtin.systemd:
    name: samba-ad-dc
  register: service_status
  changed_when: false

- name: Final determination of target_interface
  ansible.builtin.set_fact:
    install_dummy: true
    target_interface: >-
      {{ iface_dummy }}
  when: smb_conf.stat.exists and service_status.status.ActiveState == "active"
